# -*- coding: utf-8 -*-
"""
Created on Mon Jun  8 08:14:10 2020

@author: SwethaBatta
"""

import random
import tkinter as tk 
import QuantumRandomNumber as qrand

window = tk.Tk()
window.geometry("400x300")
window.title("Rock Paper Scissors Game")

class RockPaperScissors(object):
    def __init__(self):
        self.USER_SCORE = 0
        self.COMP_SCORE = 0
        self.USER_CHOICE = ""
        self.COMP_CHOICE = "" 
        self.WINNER = ""
        self.inputs = []
        self.qrand = qrand
    
    '''
    This function adds user's input to the array inputs[]
    If the user repeats the same input thrice, this function returns True, else returns False
    '''
    def checkInputRepeat(self, choice):
        self.inputs.append(choice)
        if len(self.inputs) >= 4:
            return self.inputs[-1] == self.inputs[-2] == self.inputs[-3]
        else:
            return False         
        
    '''
    Maps user's choice to a number
    '''
    def choice_to_number(self, choice):
        rps = {'rock':0,'paper':1,'scissor':2}
        return rps[choice]
    
    '''
    Maps selected number to a choice
    '''
    def number_to_choice(self, number):
        rps={0:'rock',1:'paper',2:'scissor'}
        return rps[number]
    
    '''
    Using python's random.choice() function to select an output for computer's choice
    '''
    def random_computer_choice(self):
        return random.choice(['rock','paper','scissor']) 
       
    '''
    Computes the score and displays in widget
    '''
    def result(self, human_choice,comp_choice):
        user = self.choice_to_number(human_choice)
        comp = self.choice_to_number(comp_choice)
    
        if(user == comp):
            self.WINNER = "Tie"
        elif((user-comp)%3 == 1):
            self.WINNER = "You win"
            self.USER_SCORE+=1
        else:
            self.WINNER = "Computer wins"
            self.COMP_SCORE+=1
            
        text_area = tk.Text(master=window,height=12,width=30,bg="#FFC0CB")
        text_area.grid(column=0,row=4)
        answer = "Your Choice: {uc} \nComputer's Choice : {cc} \n\nYour Score : {u} \nComputer Score : {c} \n\n Who won: {w}".format(uc=self.USER_CHOICE,cc=self.COMP_CHOICE,u=self.USER_SCORE,c=self.COMP_SCORE, w=self.WINNER)    
        text_area.insert(tk.END,answer)
    
    '''
    Computes a random choice for computer upon checking for user's input
    '''
    def action(self, choice):
        self.USER_CHOICE=choice      
        #If the user is repeating the same choice more than thrice consecutively, computer also returns to the same choice
        #else computer chooses a random number generated by quantum superposition property
        if self.checkInputRepeat(self.USER_CHOICE):
            self.COMP_CHOICE = self.USER_CHOICE
        else:
            self.COMP_CHOICE = self.number_to_choice(self.qrand.rand_int()%3)
        self.result(self.USER_CHOICE, self.COMP_CHOICE)
    

if __name__ == '__main__':
    rps = RockPaperScissors()
     
    '''
    Widget to accept user's input 
    '''  
    button1 = tk.Button(text="       Rock       ", bg="lightblue",  command= lambda : rps.action('rock'))
    button1.grid(column=0,row=1)
    button2 = tk.Button(text="       Paper      ", bg="yellow",     command= lambda : rps.action('paper'))
    button2.grid(column=0,row=2)
    button3 = tk.Button(text="      Scissor     ", bg="lightgreen", command= lambda : rps.action('scissor'))
    button3.grid(column=0,row=3)
    window.mainloop()